import '../styles/globals.css'
import Navbar from '../components/Navbar'
import Head from 'next/head'


function MyApp({ Component, pageProps }) {
  return (
  <>
  <Head>
        <title>HuntingCoder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  <Navbar/>
  <Component {...pageProps} />
  </>)
}

export default MyApp
